-- MySQL Script generated by MySQL Workbench
-- Tue Nov  9 21:08:15 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pmo_pipeline
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pmo_pipeline` ;

-- -----------------------------------------------------
-- Schema pmo_pipeline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pmo_pipeline` DEFAULT CHARACTER SET utf8 ;
USE `pmo_pipeline` ;

-- -----------------------------------------------------
-- Table `pmo_pipeline`.`ProjectType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pmo_pipeline`.`ProjectType` ;

CREATE TABLE IF NOT EXISTS `pmo_pipeline`.`ProjectType` (
  `ProjectTypeId` INT NOT NULL AUTO_INCREMENT,
  `ProjectType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ProjectTypeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pmo_pipeline`.`ValueStream`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pmo_pipeline`.`ValueStream` ;

CREATE TABLE IF NOT EXISTS `pmo_pipeline`.`ValueStream` (
  `ValueStreamId` INT NOT NULL AUTO_INCREMENT,
  `ValueStream` VARCHAR(45) NULL,
  PRIMARY KEY (`ValueStreamId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pmo_pipeline`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pmo_pipeline`.`Category` ;

CREATE TABLE IF NOT EXISTS `pmo_pipeline`.`Category` (
  `CategoryId` INT NOT NULL AUTO_INCREMENT,
  `Category` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`CategoryId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pmo_pipeline`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pmo_pipeline`.`Project` ;

CREATE TABLE IF NOT EXISTS `pmo_pipeline`.`Project` (
  `ProjectId` INT NOT NULL AUTO_INCREMENT,
  `ProjectTypeId` INT NULL,
  `ValueStreamId` INT NULL,
  `CategoryId` INT NULL,
  `Archived` TINYINT NOT NULL DEFAULT 0,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ProjectId`),
  INDEX `ProjectTypeId_idx` (`ProjectTypeId` ASC) VISIBLE,
  INDEX `ValueStream_ValueStreamId_Project_ValueStreamId_idx` (`ValueStreamId` ASC) VISIBLE,
  INDEX `Project_ProjectId_ResourceDemand_ProjectId_idx` (`CategoryId` ASC) VISIBLE,
  CONSTRAINT `ProjectType_ProjectTypeId_Project_ProjectTypeId`
    FOREIGN KEY (`ProjectTypeId`)
    REFERENCES `pmo_pipeline`.`ProjectType` (`ProjectTypeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ValueStream_ValueStreamId_Project_ValueStreamId`
    FOREIGN KEY (`ValueStreamId`)
    REFERENCES `pmo_pipeline`.`ValueStream` (`ValueStreamId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Category_CategoryId_Project_CategoryId`
    FOREIGN KEY (`CategoryId`)
    REFERENCES `pmo_pipeline`.`Category` (`CategoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pmo_pipeline`.`Area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pmo_pipeline`.`Area` ;

CREATE TABLE IF NOT EXISTS `pmo_pipeline`.`Area` (
  `AreaId` INT NOT NULL AUTO_INCREMENT,
  `Area` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AreaId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pmo_pipeline`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pmo_pipeline`.`Location` ;

CREATE TABLE IF NOT EXISTS `pmo_pipeline`.`Location` (
  `LocationId` INT NOT NULL AUTO_INCREMENT,
  `Location` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`LocationId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pmo_pipeline`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pmo_pipeline`.`Role` ;

CREATE TABLE IF NOT EXISTS `pmo_pipeline`.`Role` (
  `RoleId` INT NOT NULL AUTO_INCREMENT,
  `Role` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`RoleId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pmo_pipeline`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pmo_pipeline`.`Employee` ;

CREATE TABLE IF NOT EXISTS `pmo_pipeline`.`Employee` (
  `EmployeeId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NULL,
  `Contract` TINYINT NOT NULL,
  `InPlace` TINYINT NOT NULL,
  `AreaId` INT NULL,
  `LocationId` INT NULL,
  `StartDate` DATE NOT NULL,
  `EndDate` DATE NULL,
  `Archived` TINYINT NOT NULL DEFAULT 0,
  `RoleId` INT NULL,
  PRIMARY KEY (`EmployeeId`),
  INDEX `Area_AreaId_Employee_AreaId_idx` (`AreaId` ASC) VISIBLE,
  INDEX `Location_LocationId_Employee_LocationId_idx` (`LocationId` ASC) VISIBLE,
  INDEX `Role_RoleId_Employee_RoleId_idx` (`RoleId` ASC) VISIBLE,
  CONSTRAINT `Area_AreaId_Employee_AreaId`
    FOREIGN KEY (`AreaId`)
    REFERENCES `pmo_pipeline`.`Area` (`AreaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Location_LocationId_Employee_LocationId`
    FOREIGN KEY (`LocationId`)
    REFERENCES `pmo_pipeline`.`Location` (`LocationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Role_RoleId_Employee_RoleId`
    FOREIGN KEY (`RoleId`)
    REFERENCES `pmo_pipeline`.`Role` (`RoleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pmo_pipeline`.`ProjectRole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pmo_pipeline`.`ProjectRole` ;

CREATE TABLE IF NOT EXISTS `pmo_pipeline`.`ProjectRole` (
  `ProjectRoleId` INT NOT NULL AUTO_INCREMENT,
  `ProjectId` INT NOT NULL,
  `RoleId` INT NOT NULL,
  `EmployeeId` INT NULL,
  `StartDate` DATE NULL,
  `EndDate` DATE NULL,
  `BudgetApproved` TINYINT NULL,
  `Archived` TINYINT NOT NULL DEFAULT 0,
  `Contract` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`ProjectRoleId`),
  INDEX `ResourceDemand_ResourceDemandId_RoleEmployeeProject_Resourc_idx` (`ProjectId` ASC) VISIBLE,
  INDEX `Role_RoleId_RoleEmployeeProjectLink_RoleId_idx` (`RoleId` ASC) VISIBLE,
  INDEX `Employee_Employee_RoleEmployeeProjectLink_EmployeeId_idx` (`EmployeeId` ASC) VISIBLE,
  CONSTRAINT `Project_ProjectId_ProjectRole_ProjectId`
    FOREIGN KEY (`ProjectId`)
    REFERENCES `pmo_pipeline`.`Project` (`ProjectId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Role_RoleId_ProjectRole_RoleId`
    FOREIGN KEY (`RoleId`)
    REFERENCES `pmo_pipeline`.`Role` (`RoleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Employee_Employee_ProjectRole_EmployeeId`
    FOREIGN KEY (`EmployeeId`)
    REFERENCES `pmo_pipeline`.`Employee` (`EmployeeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pmo_pipeline`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pmo_pipeline`.`User` ;

CREATE TABLE IF NOT EXISTS `pmo_pipeline`.`User` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
